CREATE USER ${DB_REPL_USER}  WITH REPLICATION ENCRYPTED PASSWORD '${DB_REPL_PASSWORD}';
CREATE DATABASE ${DB_DATABASE};

\c ${DB_DATABASE};

CREATE TABLE IF NOT EXISTS Emails(
    EmailID SERIAL PRIMARY KEY,
    Email  VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS PhoneNumbers(
    PhoneNumberID SERIAL PRIMARY KEY,
    PhoneNumber VARCHAR(20) NOT NULL
);
INSERT INTO Emails(Email) VALUES('test@test.ru');
INSERT INTO Emails(Email) VALUES('kate@gmail.com');
INSERT INTO PhoneNumbers(PhoneNumber) VALUES('8926789032');
INSERT INTO PhoneNumbers(PhoneNumber) VALUES('+78956736523');


